# Copyright 2026, Versioneer (https://versioneer.at)
# SPDX-License-Identifier: Apache-2.0

site_name: packageR
site_url: https://package-r.versioneer.at/
repo_url: https://github.com/versioneer-tech/package-r
repo_name: versioneer-tech/package-r
copyright: "Copyright &copy; 2026, Versioneer"
nav:
  - Home: index.md
  - Get started:
      - Run packageR: how-to-guides/run-package-r.md
  - User guides:
      - Work with objects: how-to-guides/work-with-objects.md
      - Share and preview data: how-to-guides/share-and-preview-data.md
  - Operator guides:
      - Configuration: how-to-guides/configuration.md
  - Reference guides:
      - HTTP API: reference-guides/http-api.md
      - Architecture:
          - ADR-001 Embedded rclone VFS: architecture/0001-use-rclone-vfs-for-object-storage.md
plugins:
  - search
  - mike
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
theme:
  name: material
  language: en
  features:
    - content.code.copy
    - search.suggest
    - toc.follow
    - toc.permalink
  logo: imgs/logo.png
  favicon: imgs/favicon.ico
  palette:
    - scheme: default
      primary: white
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/versioneer-tech/package-r
      name: package-r on GitHub
    - icon: fontawesome/solid/copyright
      link: https://versioneer.at
      name: Versioneer
  version:
    provider: mike
